Improve type declaration for errors
fastify/fastify-sensible pull request #147
Opened 2023-10-11 15:45 UTC by arthurfiorette

This PR extends #146, as I'd like it being merged fast, I also added requested type tests and jsdoc.

This also adds exports to 3 types inside `lib/httpError`: `HttpErrorCodes`, `HttpErrorNames` and `HttpErrors.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-10-12 21:39 UTC, gurgunday approved these changes
lgtm

2023-10-14 19:48 UTC, arthurfiorette commented
Hey @gurgunday, is there anything else needed to merge this PR?

2023-10-14 20:02 UTC, gurgunday commented
I restrain from merging type PRs without 2 approvals 😁

I’ll request another review

2023-10-15 06:18 UTC, Fdawgs requested changes
Thanks for the PR.

Can you please rewrite the JSDoc description to not use 'you'?
See our[ style guide here](https://fastify.dev/docs/latest/Guides/Style-Guide#when-to-avoid-the-second-person-you-as-the-pronoun). :)

2023-10-16 03:33 UTC, arthurfiorette commented
@Fdawgs done! I also updated examples regarding schema id to use camel case `HttpError` type, which is the usual standard.

2023-10-17 12:59 UTC, mcollina commented
Code still LGTM @Fdawgs are you ok with the change?

2023-10-17 13:00 UTC, Fdawgs approved these changes

2023-10-17 13:00 UTC, merged